version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
        - app-quipux-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-quipux-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - app-quipux-network

  keycloak:
    image: keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8088:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    command:
      - start-dev
    networks:
      - app-quipux-network

  app:
    build: musicApp
    ports:
      - "8082:8082"
    depends_on:
      - keycloak
    networks:
        - app-quipux-network

  backend-1:
    build:
      context: ./musicApp
    ports:
      - "8083:8080"
    expose:
      - "8083"
    networks:
      - app-quipux-network
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/musicapp_db
      DB_USER: sa
      DB_PASSWORD: password
      KAFKA_SERVER: kafka:29092
      KEYCLOAK_CLIENT_SECRET: "INSERTE CLIENT SECRET AQUI PARA USAR ENDPOINT CON AUTH"


  backend-2:
    build:
      context: ./musicAppPersist
    ports:
      - "8085:8080"
    expose:
        - "8085"
    networks:
      - app-quipux-network
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/musicapp_db
      DB_USER: sa
      DB_PASSWORD: password
      KAFKA_SERVER: kafka:29092


  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musicapp_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-quipux-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "localhost"]
      interval: 3s
      retries: 3
      timeout: 5s

volumes:
  keycloak_data:
  h2-data:

networks:
  app-quipux-network:
    driver: bridge
